1.Develop a python program to read n digit integer number and separate the integer number and display each digit


In [1]:
n=int(input("enter the number of digits:"))
if n>0:
    number=int(input(f"enter a {n}-digit integer:"))
    if number>=10**(n-1) and number<10**n:
        for i in range (n):
            digit=number//(10**(n-1))
            print(digit)
            number%=10**(n-1)
            n-=1
    else:
        print(f"please enter a {n}-digit integer")
else:
    print("please enter a valid number of digits (greater than 0).")

enter the number of digits:4
enter a 4-digit integer:5678
5
6
7
8


2.Develop a python program to accept the number and display then in sorted order using a minimum number of if else statement

In [2]:
a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
c=int(input("enter the third number:"))
d=int(input("enter the fourth number:"))
if a<b:a,b=b,a
if c<d:c,d=d,c
if a<c:a,c=c,a
if b<d:b,d=d,b
if b<c:b,c=c,b
print("the sorted numbers are :",a,b,c,d)

enter the first number:7
enter the second number:1
enter the third number:9
enter the fourth number:3
the sorted numbers are : 9 7 3 1


4.Develop a program for checking if a given n digit number is palindrome or not

In [11]:
number=int(input("enter an n-digit number:"))
original_number=number
reversed_number=0
while number>0:
    digit=number%10
    reversed_number=reversed_number*10+digit
    number//=10
if original_number==reversed_number:
    print("palindrome")
else:
    print("not a palindrome")


enter an n-digit number:12321
palindrome


5.Develop a python script to display a muiltiplication table for given integer

In [8]:
n=int(input("enter an integer for the multiplication table:"))
print(f"multiplication table for {n}:")
for i  in range (1,11):
    result=n*i
    print(f"{n}*{i}={result}")

enter an integer for the multiplication table:3
multiplication table for 3:
3*1=3
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
3*10=30


3.Develop  python scripts to calculate the mean,median,mode,variance and standard deviation of n integer number

In [21]:
n=int(input("enter the number of elements:"))
numbers=[int(input(f"enter numbers{i+1}:"))for i in range(n)]
mean=sum(numbers)/n
numbers.sort()
if n%2==0:
    median=(numbers[n//2-1]+numbers[n//2])/2
else:
    median=numbers[n//2]
frequency={num:numbers.count(num)for num in numbers}
max_count=max(frequency.values())
mode=[k for k, v in frequency.items() if v==max_count]
if len(mode)==n:
    mode="No mode"
mean_difference_squared_sum=sum((x-mean)**2 for x in numbers)
variance_sample=mean_difference_squared_sum/(n-1) if n>1 else 0
variance_population=mean_difference_squared_sum/n
std_deviation_sample=variance_sample**0.5
std_deviation_population=variance_population**0.5
print(f"mean:{mean}")
print(f"median:{median}")
print(f"mode:{mode}")
print(f"sample variance:{variance_sample}")
print(f"population variance:{variance_population}")
print(f"sample standard deviation:{std_deviation_sample}")
print(f"population standard deviation:{std_deviation_population}")

enter the number of elements:6
enter numbers1:4
enter numbers2:8
enter numbers3:6
enter numbers4:5
enter numbers5:3
enter numbers6:9
mean:5.833333333333333
median:5.5
mode:No mode
sample variance:5.366666666666667
population variance:4.472222222222222
sample standard deviation:2.316606713852541
population standard deviation:2.1147629234082532


In [22]:
n=5
while n>0:
    print(n)
    n-=1
else:
    print("loop finished without break:")
        
    

5
4
3
2
1
loop finished without break:


In [24]:
n=range(1,4)
for j in n:
    print("Factorial of "+str(j)+"is:")
    mul=1
    for i in range(1,j+1):
        mul=mul*i
        print(mul)

Factorial of 1is:
1
Factorial of 2is:
1
2
Factorial of 3is:
1
2
6


6.Python program to rotate right about a given position in that list and display them.

In [14]:
number=int(input("enter integer number:"))
revs_number=0
while(number>0):
    remainder=number%10
    revs_number=((revs_number)*10)+remainder
    number=number//10
print("the reverse number is :{}". format(revs_number))    
    

enter integer number:45687
the reverse number is :78654


7.Develop a python script to interchange the digits of a given integer number


In [21]:
def interchange_digits(number,pos1,pos2):
    number_str=str(number)
    number_list=list(number_str)
    number_list[pos1-1],number_list[pos2-1]=number_list[pos2-1],number_list[pos1-1]
    interchanged_number=int(''.join(number_list))
    return interchanged_number
number=int(input('enter the user input:'))
pos1=int(input('enter the 1st person which you want to swap:'))
pos2=int(input('enter the 2nd person which you want to swap:'))
interchanged_number=interchange_digits(number,pos1,pos2)
print('original number :',number)
print('interchanged number:',interchanged_number)

enter the user input:23456
enter the 1st person which you want to swap:3
enter the 2st person which you want to swap:5
original number : 23456
interchanged number: 23654


In [22]:
n=int(input("enter a natural number:"))
i=1
while i<=n:
    print(i, end='')
    i+=1

enter a natural number:5
12345

In [24]:
n=int(input("enter a natural number:"))
i=2
while i<=n:
    print(i, end='')
    i+=2

enter a natural number:10
246810

In [25]:
n=int(input("enter a natural number:"))
i=1
while i<=n:
    print(i, end='')
    i+=2

enter a natural number:10
13579

In [26]:
n=int(input("enter a natural number:"))
total_sum=0
i=1
while i<=n:
    total_sum+=i
    i+=1
print("the sum of natural mo. upto ",n,"is:",total_sum)    

enter a natural number:20
the sum of natural mo. upto  20 is: 210


8. Develop a python program to capitalize a given list



In [7]:
def capitalize_strings(string_list):
    return[s.capitalize() for s in string_list]
input_strings=['hello','good','how','simple']
capitalized_strings=capitalize_strings(input_strings)
print(capitalized_strings)

['Hello', 'Good', 'How', 'Simple']


9.Using a dictionary ,develop a python program to determine and print the number of duplicate words in a sentence

In [21]:
def count_duplicate_words(sentence):
    words=sentence.split()
    word_count={}
    for word in words:
        word=word.lower()
        if word in word_count:
            word_count[word]+=1
        else:
            word_count[word]=1
    duplicates={word:count for word,count in word_count.items() if count>1}
    if duplicates:
        print("Duplicate words om their counts:")
        for word,count in duplicates.items():
            print(f"{word}:{count}")
    else:
        print("no duplicate wors found")
sentence=input("enter a sentence:")
count_duplicate_words(sentence)

enter a sentence:hi i am tom, hi i am jerry
Duplicate words om their counts:
hi:2
i:2
am:2


In [34]:
sample_dict={"name":"Jessa",10:"Mobile"}
print(sample_dict)
person={"name":"Jessa","telephone":[1178,2563,4569]}
print(person)
keys={'12','23','1','5','7','11'}
value=0
sample=dict.fromkeys(keys,value)
print(sample)

{'name': 'Jessa', 10: 'Mobile'}
{'name': 'Jessa', 'telephone': [1178, 2563, 4569]}
{'11': 0, '1': 0, '5': 0, '7': 0, '12': 0, '23': 0}


In [33]:
d_state={1:'Delhi',2:'Mumbai',3:'Chennai',4:'Kolkata'}
print(d_state.get(1))

Delhi


In [37]:
dict_state={1:'Delhi',2:'Mumbai',3:'Chennai',4:'Kolkata'}
dict_state.keys()


dict_keys([1, 2, 3, 4])

In [38]:
d_state={1:'Delhi',2:'Mumbai',3:'Chennai',4:'Kolkata'}
d_state.values()


dict_values(['Delhi', 'Mumbai', 'Chennai', 'Kolkata'])

10.Develop a python program to read NumPy array and print row(sum,mean,std)and column(sum,mean,std)

In [3]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data )
print("numpy array")
print(data)
print("_______________")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("row sum")
print(totalr)
print("column sum")
print(totalc)
print("_______________")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("row mean")
print(meanr)
print("column mean")
print(meanc)
print("_______________")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("row STD")
print(stdr)
print("column STD")
print(stdc)

numpy array
[[1 2 3]
 [4 5 6]]
_______________
row sum
[ 6 15]
column sum
[5 7 9]
_______________
row mean
[2. 5.]
column mean
[2.5 3.5 4.5]
_______________
row STD
[0.81649658 0.81649658]
column STD
[1.5 1.5 1.5]


In [12]:
import csv
file=open('filename.csv',mode='r')
csv_reader=csv.reader(file,delimiter=',')
line_count=0

for row in csv_reader:
    if line_count==0:
        print(f'column name are {",".join(row)}')
        line_count+=1
    else:
        print(f'\t{row[0]} works in the {row[1]} department,and was born in {row[2]}.')
        line_count+=1
print(f'processed {line_count} lines.')  
file.close()

column name are name,department,birthday_month
	John Smith works in the Accounting  department,and was born in May.
	Erica works in the IT department,and was born in June.
	Rocky works in the HR department,and was born in April.
processed 4 lines.


In [19]:
import numpy as np
a=np.arange(4)
b=np.arange(5)
print(a)
a+=4
print(a)

[0 1 2 3]
[4 5 6 7]
